name: check

on:
  pull_request:
  push:
    branches:
      - master

jobs:

  test:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os:
          - ubuntu-latest
        python-version:
          - "3.8"
          - "3.9"
          - "3.10.0-alpha - 3.10"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{matrix.python-version}}
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cache/pip
            .tox
          key: >-
            ${{runner.os}} pip ${{matrix.python-version}}
            ${{hashFiles('requirements-test.txt', 'setup.cfg')}}
      - name: Install dependencies
        run: |
          python3 -m pip install tox-gh-actions
      - name: Run tests
        run: |
          tox --skip-missing-interpreters false
        env:
          PYTEST_ADDOPTS: --color=yes
          TOX_TESTENV_PASSENV: PYTEST_ADDOPTS
